language: node_js
node_js:
  - lts/*
services:
  - docker

before_install:
  - docker build -t rtrvl/starbeats:latest -f Dockerfile.dev .

script:
  - docker run rtrvl/starbeats yarn test --coverage --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Starbeats"
  env: "Starbeats-env"
  bucket: elasticbeanstalk-us-east-1-398485943999
  bucket_path: "Starbeats"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
