language: node_js
node_js:
  - lts/*
services:
  - docker

before_install:
  - docker build -t rtrvl/starbeats:latest -f Dockerfile.dev .

script:
  - docker run rtrvl/starbeats yarn test --coverage --watchAll=false