branch-defaults:
  master:
    environment: Starbeats-$CIRCLECI_BRANCH
  develop:
    environment: Starbeats-$CIRCLECI_BRANCH
global:
  application_name: Starbeats
  default_platform: 64bit Amazon Linux 2/3.4.16
  default_region: us-east-1
  sc: git