version: 2.1
jobs:
  testme:
    docker:
      - image: cimg/node:14.19
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: node --version
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # run build
      - run: ls
      - run:
          name: build docker image from dckerfile.dev
          command: docker build -f Dockerfile.dev -t rtrvl/test-build:latest .
      # run mah test
      - run:
          name: create container and run test
          command: docker run rtrvl/test-build yarn test --coverage --watchAll=false
  deployme:
      docker:
       - image: cimg/python:3.10
      steps:
        - checkout
        - run: pip3 --version
        - run:
            working_directory: /
            name: install ebcli
            command: pip3 install awsebcli --upgrade --user
        - run: eb --version
        - run:
            name: deploy with ebcli
            command: eb deploy Starbeats-$CIRCLE_BRANCH

      # # build and push Docker image
      # - run: |
      #     TAG=0.1.$CIRCLE_BUILD_NUM
      #     docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
          # echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          # docker push CircleCI-Public/circleci-demo-docker:$TAG
workflows:
  test-then-deploy:
    jobs:
      - testme
      - deployme:
          context: aws-creds
          filters:
            branches:
              only:
                - master
          requires:
            - testme
